# Customizations only - defaults inherited from lazygit

gui:
  theme:
    activeBorderColor: [white, bold]
    inactiveBorderColor: [gray]
    optionsTextColor: [gray]
    selectedLineBgColor: [default, bold]
    selectedRangeBgColor: [default, bold]
    unstagedChangesColor: [yellow]
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never # syntax-highlighted diffs
os:
  editCommand: nvim
customCommands:
  - key: '<c-a>'
    command: 'git commit --amend --no-edit'
    context: files
    description: Amend without editing message
  - key: '<c-r>'
    command: 'git reset --soft HEAD~1'
    context: commits
    description: Soft reset to previous commit
  - key: C
    command: 'git checkout {{.SelectedLocalCommit.Sha}}'
    context: commits
    description: Checkout commit
