# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1C1A)
$foreground = rgb(E0E0BA)
$color0 = rgb(414240)
$color1 = rgb(12160F)
$color2 = rgb(12160F)
$color3 = rgb(12160F)
$color4 = rgb(171B12)
$color5 = rgb(484D1C)
$color6 = rgb(7D7D2C)
$color7 = rgb(CBCB95)
$color8 = rgb(8E8E68)
$color9 = rgb(181D14)
$color10 = rgb(181D14)
$color11 = rgb(181D14)
$color12 = rgb(1F2517)
$color13 = rgb(606626)
$color14 = rgb(A7A73B)
$color15 = rgb(CBCB95)
